# Generated by Django 4.0.1 on 2022-01-17 08:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.TextField()),
                ('identy_number', models.TextField()),
                ('regist_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('site', models.TextField()),
                ('brand', models.TextField(blank=True)),
                ('product_url', models.URLField()),
                ('product_name', models.TextField()),
                ('stock', models.BooleanField()),
                ('price', models.IntegerField()),
                ('shipping_price', models.IntegerField(null=True)),
                ('weight', models.TextField(blank=True)),
                ('volume', models.TextField(blank=True)),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), size=None)),
            ],
        ),
    ]
