# Generated by Django 3.1.3 on 2021-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.TextField()),
                ('identy_number', models.TextField()),
                ('regist_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('site', models.TextField()),
                ('brand', models.TextField()),
                ('product_url', models.TextField()),
                ('product_name', models.TextField()),
                ('stock', models.BooleanField()),
                ('price', models.FloatField()),
                ('shipping_price', models.FloatField()),
                ('weight', models.TextField(blank=True)),
                ('volume', models.TextField(blank=True)),
                ('option', models.DateTimeField()),
            ],
        ),
    ]
