# Generated by Django 4.0.3 on 2022-03-03 17:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.TextField()),
                ('identy_number', models.TextField()),
                ('regist_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('site', models.TextField()),
                ('brand', models.TextField(blank=True)),
                ('product_url', models.URLField()),
                ('product_name', models.TextField()),
                ('product_title', models.TextField(null=True)),
                ('stock', models.BooleanField()),
                ('price', models.IntegerField()),
                ('sale_price', models.IntegerField(null=True)),
                ('shipping_price', models.IntegerField(null=True)),
                ('weight', models.TextField(blank=True)),
                ('volume', models.TextField(blank=True)),
                ('option', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTokken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_usertokken', models.TextField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('foreign_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Ebay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('brand', models.TextField(null=True)),
                ('style', models.TextField(null=True)),
                ('color', models.TextField(null=True)),
                ('department', models.TextField(null=True)),
                ('pattern', models.TextField(null=True)),
                ('features', models.TextField(null=True)),
                ('fabricType', models.TextField(null=True)),
                ('occasion', models.TextField(null=True)),
                ('material', models.TextField(null=True)),
                ('foreign_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
