# Generated by Django 4.0.1 on 2022-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='option',
            field=models.TextField(max_length=100),
        ),
    ]
