# Generated by Django 4.0.3 on 2022-03-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_description_middle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description_Bottom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ebay',
            name='description',
        ),
    ]
