# Generated by Django 4.0.1 on 2022-01-17 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=100),
        ),
    ]
