# Generated by Django 4.0.3 on 2022-03-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_usertokken_ebay_refreshtokken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokken',
            name='refresh_expired',
            field=models.TextField(null=True),
        ),
    ]
