# Generated by Django 4.0.3 on 2022-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_item_category_ebay_required_spec_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='policy_number',
            field=models.IntegerField(null=True),
        ),
    ]
